spring:
  data:
    mongodb:
      uri: ${DB_URI}
management:
  endpoints:
    jmx:
      exposure:
        include: health,info,beans
  info:
    java:
      enabled: true
    env:
      enabled: true

app:
  api:
    runner:
      url: "http://cicd-runner-service:8080"
    registry:
      url: "http://registry-service:5000"
    github:
      url: "https://github.com"
      id: ${GITHUB_ID}
      secret: ${GITHUB_SECRET}
    github-api:
      url: "https://api.github.com"