spring:
  data:
    mongodb:
      uri: ${DB_URI}
management:
  endpoints:
    jmx:
      exposure:
        include: health,info,beans
  info:
    java:
      enabled: true
    env:
      enabled: true

app:
  api:
    pipeline:
      url: "http://pipeline-service:8080"
    registry:
      url: "http://registry-service:5000"